In [93]:
import numpy as np

## Numpy

- [a] -> 1-D array

- [ [a], [b] ] -> 2-D array

- [ [ [a], [b], [c] ], [ [d], [e], [f] ] ] -> 3-D array

In [94]:
my_matrix = [[[1,2,3], [4,5,6], [7,8,9]], [[1,2,7], [2,3,5], [3,4,6]]]
my_matrix

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 7], [2, 3, 5], [3, 4, 6]]]

In [95]:
np.array(my_matrix)

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 7],
        [2, 3, 5],
        [3, 4, 6]]])

###

- arange function provides array with values from starting index to (ending index - 1) 

        ex: np.arange(1,10) -> Gives elements from 1 to 9

- It may contain a 3rd arguement with step size

In [96]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [97]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

In [98]:
np.arange(1, 2, 0.1)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

###

- zeros function will give an array of zeros; zeros will be floating 

        ex: np.zeros(10) -> Gives array of 10 floating zeros

- can also give 2-D or 3-D arrays

- np.zeros((no. of arrays, rows, columns))

In [99]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [100]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [101]:
np.zeros((5,5,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [102]:
np.zeros((3,2,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

###

- np.ones is same as np.zeros

In [103]:
np.ones((4,3,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

###

- np.linspace(x,y,z) finds z elements that are evenly spaced between x and y

        ex: np.linspace(0,10,3) -> 3 evenly spaced elements b/w 0 and 10

In [104]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [105]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

###

- eye gives an identity matrix

        ex: np.eye(4) -> Gives a 4x4 identity matrix

In [106]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

###

- Random numbers are also called pseudo random numbers

- rand gives any random numbers b/w 0 and 1

- It can give 1-D, 2-D.... array

        ex: np.random.rand(2) -> 2 random numbers b/w 0 and 1

In [107]:
np.random.rand(2)

array([0.81146098, 0.64027806])

In [108]:
np.random.rand(5,5)

array([[0.62477951, 0.14550751, 0.5702159 , 0.0651125 , 0.31341257],
       [0.21706577, 0.52695039, 0.42710838, 0.98263043, 0.14045149],
       [0.7484116 , 0.78884039, 0.73039662, 0.84561834, 0.55619038],
       [0.05686271, 0.88672457, 0.31441695, 0.56039187, 0.2540144 ],
       [0.9349621 , 0.03424494, 0.68654496, 0.43893494, 0.97772095]])

###

- randn -> gives you random numbers centered around zero with higher chances of being close to zero; numbers b/w -1 and 1 are given with common mean and mod

- randn generates random numbers each time with different seed; seed functiion provides a set of numbers for generating

In [1]:
np.random.seed(100)

NameError: name 'np' is not defined

In [110]:
np.random.randn(2)

array([-1.74976547,  0.3426804 ])

In [111]:
random_array = np.random.randn(3, 4)
print(random_array)

[[ 1.1530358  -0.25243604  0.98132079  0.51421884]
 [ 0.22117967 -1.07004333 -0.18949583  0.25500144]
 [-0.45802699  0.43516349 -0.58359505  0.81684707]]


###

- np.random.randint gives some random numbers b/w given numbers

        ex: np.random.randint(1,100,10) -> 10 random integers b/w 1 and 100

In [112]:
np.random.randint(1,100,10)

array([92, 60, 68,  8, 50, 48, 66, 62, 15, 56])

In [113]:
mynum = np.random.randint(1,100,25)

In [114]:
mynum

array([72, 81,  3, 95, 20, 99, 64, 54, 28, 57, 31, 49, 48, 40, 39, 45, 19,
       65, 57, 35, 54, 75, 18, 73, 14])

###

- reshape returns the array with same data but after reshapping it

        ex: mynum = np.random.randInt((1,100,25))
            mynum.reshape(5,5) -> Gives a 5x5 2-D array of numbers in mynum 

In [115]:
mynum.reshape(5,5)

array([[72, 81,  3, 95, 20],
       [99, 64, 54, 28, 57],
       [31, 49, 48, 40, 39],
       [45, 19, 65, 57, 35],
       [54, 75, 18, 73, 14]])

In [116]:
mynum2 = np.random.randint(1,100,16)

In [117]:
mynum2.reshape(2,2,4)

array([[[31, 18, 54, 69],
        [51, 92, 92, 84]],

       [[54, 79,  1, 14],
        [58, 77,  4, 71]]])

###

- max() -> Gives maximum no. in the array

- argmax() -> Gives index of maximum no. in the array

In [118]:
num1 = np.random.randint(1,100,10)

In [119]:
num1

array([ 4, 85, 80, 11, 88, 61,  4, 49, 53, 44])

In [120]:
num1.max()

88

In [121]:
num1.argmax()

4

###

- dtype -> Tells us about the type of data present in an numpy array


In [122]:
num1.dtype

dtype('int32')