In [1]:
import pandas as pd 
import numpy as np 

- Big data vs High Dimensional Data

- High Dimensional Data as well as Big Data are structured data i.e. they are labelled

- Example of big data:
        
        - Bank details

- If number of features (Columns) in data becomes high (>100) but rows are less, it becomes high dimensional data

- If number of features as well as rows are high (Millions), it becomes big data

- Big data is taken from a number of sources

- DataFrame is basically a collection of arrays i.e. Each row or column is seen as a 1-D Array

- This Dataframe contains multiple 1-D arrays forming 2-D arrays which are further called series

<img src = 'Lec.png'>

In [2]:
a = [123,345,556,456,78,233]
# np.array(a)

In [3]:
a = {'AccNo.':10, 'AccHolder':'Amit'}              # will be created as a single object if converted into array

In [4]:
b = np.array(a)

In [5]:
b

array({'AccNo.': 10, 'AccHolder': 'Amit'}, dtype=object)

In [6]:
b.shape              # Tells us about number of elements in a row

()

In [7]:
b.ndim               # ndim property that tells us about dimension of array

0

- If we get 0 from ndim, the passed element is not an array

- It also tells us that only a single element is present

In [8]:
np.array(100).ndim

0

In [9]:
type(b)

numpy.ndarray

In [10]:
c = [1]
d = np.array(c)

In [11]:
d.ndim

1

- In case of list, ndim gives output one because it already has one row and column

In [12]:
e = 1
f = [1]
g = [[1]]
h = [[[1]]]

i = np.array(e)                # Gives 0-D array; No rows and columns are present
j = np.array(f)                # Gives 1-D array
k = np.array(g)                # Gives 2-D array
l = np.array(h)                # Gives 3-D array

In [13]:
print(i.ndim)
print(j.ndim)
print(k.ndim)
print(l.ndim)

0
1
2
3


- Arrays are mutable

In [14]:
a = [ [1,2,3,6,7], [4,5,6,8,9], [7,8,9,1,2], [43,56,78,-1,3] ]                 # 2-D array

In [15]:
nparray = np.array(a)

In [16]:
print(nparray)

[[ 1  2  3  6  7]
 [ 4  5  6  8  9]
 [ 7  8  9  1  2]
 [43 56 78 -1  3]]


In [17]:
#indexing

nparray[1,1]

5

### Slicing

In [18]:
nparray[1:3, 1:3]               # (Row index:Column index), (element/row index:ending index for next row) 

array([[5, 6],
       [8, 9]])

In [19]:
slice1 = nparray[1:3, 1:3]            

In [20]:
slice1[1,1]                     # Accessing elements of slice1

9

In [21]:
slice1[1,1] = 90                # Changing elements of slice1

In [22]:
slice1

array([[ 5,  6],
       [ 8, 90]])