- Data is initially in the form of 2-D array

In [1]:
a = ['Delhi', 162, 200, 150], ['Chandigarh', 180, 227, 115], ['Shimla', 200, 115, 310]

In [2]:
for i in a: print(i)

['Delhi', 162, 200, 150]
['Chandigarh', 180, 227, 115]
['Shimla', 200, 115, 310]


In [3]:
print(a)
print(type(a))

(['Delhi', 162, 200, 150], ['Chandigarh', 180, 227, 115], ['Shimla', 200, 115, 310])
<class 'tuple'>


In [4]:
b = 1,2,3

In [5]:
print(b)
print(type(b))

(1, 2, 3)
<class 'tuple'>


In [20]:
b = [[162,200,150], [180,220,115], [200,115,310]] 

In [21]:
print(b)
print(type(b))


[[162, 200, 150], [180, 220, 115], [200, 115, 310]]
<class 'list'>


###

## Numpy

In [22]:
import numpy as np

In [23]:
np.array([1,2,3,4,5])              # array function converts any mentioned data type into array

array([1, 2, 3, 4, 5])

In [24]:
a = [2,234,45,456,324,67,567,567,567]
type(a)

list

In [25]:
arr = np.array(a)

In [26]:
print(a)

[2, 234, 45, 456, 324, 67, 567, 567, 567]


In [13]:
arr

array([  2, 234,  45, 456, 324,  67, 567, 567, 567])

In [14]:
b 

[[162, 200, 150], [180, 220, 115], [200, 115, 310]]

In [15]:
twoDarr = np.array(b)

In [16]:
twoDarr                # Let's say rows are states and columns are months

array([[162, 200, 150],
       [180, 220, 115],
       [200, 115, 310]])

In [17]:
import pandas as pd

In [27]:
df = pd.DataFrame(twoDarr)
df

0    1    2
0  162  200  150
1  180  220  115
2  200  115  310

In [28]:
df = pd.DataFrame(twoDarr, index=[i[0] for i in a], columns=['June', 'July', 'August'])

TypeError: 'int' object is not subscriptable

In [ ]:
df

June  July  August
Delhi        162   200     150
Chandigarh   180   220     115
Shimla       200   115     310

In [ ]:
li = df.index.values
for i in li: print(i)

Delhi
Chandigarh
Shimla


In [ ]:
li = df.columns.values 
for i in li: print(i)

June
July
August


In [ ]:
df['June']                           # Provides all info in the month of june

Delhi         162
Chandigarh    180
Shimla        200
Name: June, dtype: int32

In [ ]:
df.iloc[0]

0    162
1    200
2    150
Name: 0, dtype: int32

In [ ]:
df.loc['Chandigarh']                 # loc function locates a specific element values into data set; loc is for getting row elements

June      180
July      220
August    115
Name: Chandigarh, dtype: int32

In [ ]:
rain_den_in_june = df['June']

In [ ]:
rain_den_in_june

Delhi         162
Chandigarh    180
Shimla        200
Name: June, dtype: int32

In [ ]:
type(rain_den_in_june)

pandas.core.series.Series

In [ ]:
l2 = list(rain_den_in_june)

In [ ]:
l2

[162, 180, 200]

In [ ]:
li = np.array(rain_den_in_june)

In [ ]:
li

array([162, 180, 200])

In [ ]:
rain_den_in_june['Chandigarh']                  # will provide the corresponding value with respect to the key

180

###

- All keys in a dictionary will be column name for a dataset

- Numeric data is automatically converted into float type

- Columns that are able to categorise the rows into a few parts is called categorial column

- Columns that are contains numeral values are called numerical columns

- Columns that are contains string values are called string columns

###

In [ ]:
mydata = {'Rollno.':10, 'Name':'Amit', 'Gender':'Male'}, {'empid':11, 'Name':'Priya', 'Gender': 'Female'}, {'Rollno.':10, 'Name':'Amit1', 'Gender':'Male'}, {'empid':11, 'Name':'Priya1', 'Gender': 'Female'} 

In [ ]:
pd.DataFrame(mydata)                 # since no empid value is provided to amit, dataset will set it as null by default

Rollno.    Name  Gender  empid
0     10.0    Amit    Male    NaN
1      NaN   Priya  Female   11.0
2     10.0   Amit1    Male    NaN
3      NaN  Priya1  Female   11.0