## Numpy

In [2]:
import numpy as np

###

- Broadcasting -> Initialising a value to an array range

In [3]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[0:5] = 100           # Broadcasting
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [5]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
slice_of_arr = arr[:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [7]:
slice_of_arr[:] = 99            # Accessing all elements; Refering to original array elements
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [8]:
arr               # Slicing will also result in change into the original array

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [9]:
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [10]:
arr2 = np.zeros(11)

arr2

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
arr2 = arr

In [12]:
print(arr)
print(arr2)

[99 99 99 99 99 99  6  7  8  9 10]
[99 99 99 99 99 99  6  7  8  9 10]


In [13]:
arr2[0] = 1000
arr

array([1000,   99,   99,   99,   99,   99,    6,    7,    8,    9,   10])

- If you'll make any changes in assigined array, original array also gets changed because of same reference

- We can make these copies using assignment of a new array

###

Deepcopy

- Copying using copy function

- Won't effect original array

In [14]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [15]:
arr_copy[0] = 0
arr_copy

array([ 0, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [16]:
arr

array([1000,   99,   99,   99,   99,   99,    6,    7,    8,    9,   10])

###

INDEXING AN 2-d ARRAY

In [17]:
arr_2d = [[5,10,15], [20,25,30], [35,40,45]]

In [18]:
arr3 = np.array(arr_2d)

In [19]:
arr3

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

- 2 ways to extract an element

In [20]:
arr3[2,1]

40

In [21]:
arr3[2][1]

40

In [22]:
arr_3d = np.array(
[
    [
        [1,2],
        [3,4]
    ],
    [
        [4,6],
        [7,8]
    ]
]
)

In [23]:
arr_3d

array([[[1, 2],
        [3, 4]],

       [[4, 6],
        [7, 8]]])

In [24]:
arr_3d[1][0][1]            # Getting 2nd row, then 1st row and then 2nd element

6

In [25]:
# 2-D array slicing

arr3[:2,1:]             # 0th row to 1st row and 1st column to all columns 

array([[10, 15],
       [25, 30]])

In [26]:
arr_3d[1,:2,1:]              # In 2nd array, 0th to 1st row and 1st to last column

array([[6],
       [8]])

###

Fancy Indexing

In [27]:
arr = [[1,2,3], [4,5,6], [7,8,9]]

for i in range(len(arr)):
    for j in range(len(arr)):
        arr[i][j] = int(input())
        
for i in range(len(arr)):
    for j in range(len(arr)):
        print(arr[i][j], end = " ")
    print() 

ValueError: invalid literal for int() with base 10: ''

In [ ]:
rows = int(input())
cols = int(input())
arr = []

for i in range(rows):
    row = []
    for j in range(cols):
        ele = int(input())
        row.append(ele)
    arr.append(row)
        
for m in range(rows):
    for n in range(cols):
        print(arr[m][n], end = " ")
    print()

3 1 2 
3 4 5 
6 7 8 


In [ ]:
a = int(input())
b = [int(input()) for x in range(a)]*a
arr = []
arr.append(b)
arr

[[1, 2, 3, 1, 2, 3, 1, 2, 3]]

In [ ]:
arr

[[1, 2, 3, 1, 2, 3, 1, 2, 3]]

In [ ]:
np.array(arr)

array([[3, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
# rows = int(input())
cols = int(input())
arr = [int(input())]*cols

for i in arr:
    print(arr)


[7, 7, 7, 7, 7]
[7, 7, 7, 7, 7]
[7, 7, 7, 7, 7]
[7, 7, 7, 7, 7]
[7, 7, 7, 7, 7]


In [ ]:
dim = int(input())
arr = []
for i in range(dim):
    row = []
    a = float(input())
    for j in range(dim):
        row.append(a)
    arr.append(row)
        
arr

[[1.0, 1.0, 1.0], [2.0, 2.0, 2.0], [3.0, 3.0, 3.0]]

In [ ]:
np.array(arr)

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [28]:
arr2d = np.zeros((10,10))
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [29]:
arr2d.shape             # Tells number of rows and columns

(10, 10)

In [30]:
arr_length = arr2d.shape[1]

In [31]:
arr_length

10

In [32]:
for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [34]:
arr2d[[2,4,6,8]]               # indexing; Given a list with row numbers to be accessed

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [ ]:
arr2d[[3,4,5,6]]

array([[3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.]])

###

In [ ]:
arr[-1:-5:-1]               # Accessing using negative index; start index: end index: step size

[[3.0, 3.0, 3.0], [2.0, 2.0, 2.0], [1.0, 1.0, 1.0]]

###

Selection

- Using brackets for selection based of comparison operator


In [ ]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
arr[arr>2]                  # Returns elements that are greater than 2

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr3>10

array([[False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
arr3[arr3>2]

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])