In [2]:
import pandas as pd
import numpy as np

## Conditional Operators

- And operator -> &

- Or operator -> |

- Not operator -> ~

- Will give bool values

In [3]:
a = [1,2,3,4,5]
a = np.array(a)

In [4]:
a

array([1, 2, 3, 4, 5])

In [5]:
a>2

array([False, False,  True,  True,  True])

###

- AND (&)

In [6]:
(a>2) & (a<5)

array([False, False,  True,  True, False])

In [7]:
a[(a>2) & (a<5)]

array([3, 4])

###

- OR (|)

In [8]:
a[(a>2) | (a<5)]

array([1, 2, 3, 4, 5])

###

- NOT (~)

In [9]:
print((a>2))
print(~ (a>2))

[False False  True  True  True]
[ True  True False False False]


###

## Arithmetic Operators

    -> +
    -> -
    -> *
    -> **
    -> /

In [10]:
arr = np.arange(0,10)

In [11]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [13]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [15]:
arr/arr                # Will give warning when division by 0, but won't give error; Replaces by nan

C:\Users\Pratham Gupta\AppData\Local\Temp\ipykernel_18924\3354632428.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr                # Will give warning when division by 0, but won't give error; Replaces by nan


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [16]:
1/arr                  # Gives warning but not an error; gives inf when we get 1/0

C:\Users\Pratham Gupta\AppData\Local\Temp\ipykernel_18924\476533325.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr                  # Gives warning but not an error; gives inf when we get 1/0


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

###

In [17]:
a = np.array([1,2,3])
b  = np.array([1,2])

In [18]:
# a + b              # Gives error because we can't broadcast 2 arrays of different shape

In [19]:
a = np.array([1,2,3])
b  = np.array([1,2,np.nan])

In [20]:
a+b

array([ 2.,  4., nan])

###

## Universal Array Functions

Some arry functions:
 
    - sqrt()
    - exp()
    - max()
    - sin()
    - log()
    - add()

In [21]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [22]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [23]:
np.max(arr)

9

In [24]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [25]:
np.log(arr)

C:\Users\Pratham Gupta\AppData\Local\Temp\ipykernel_18924\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [26]:
np.add(arr, arr)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])